const $=id=>document.getElementById(id);
const s={mod:"QPSK",scheme:"跳频传输",channel:"AWGN",rate:250,snr:18,view:"wave",stage:0};
const mods={
 "2ASK":[1,1.15,"用两个幅度表示 0 和 1，结构直观，但对幅度噪声较敏感。"],
 "2FSK":[1,1.8,"用两个频率承载二进制信息，包络稳定，适合观察频率切换。"],
 BPSK:[1,1.05,"用相差 180° 的两个相位传输比特，具有良好的抗噪声性能。"],
 QPSK:[2,1.05,"每个符号携带 2 bit，在带宽效率与实现复杂度之间取得平衡。"],
 "16QAM":[4,1.05,"幅度与相位联合调制，每个符号携带 4 bit，但需要更高信噪比。"],
 MSK:[1,1.5,"连续相位、恒包络的最小频移键控，频谱旁瓣特性良好。"],
 OFDM:[4,.92,"多个正交子载波并行传输，适合频率选择性信道。"]};
const schemes={"常规传输":["单载波","1×","数据映射后直接调制到固定载频，适合学习基础调制与解调。"],"直接序列扩频":["DSSS","8×","用高速伪随机码扩展信号带宽，获得处理增益和抗窄带干扰能力。"],"跳频传输":["FHSS","16 信道","载波按照跳频序列在多个信道间切换，适合演示 ELRS 类跳频过程。"],"OFDM 多载波":["OFDM","8 子载波","把高速数据拆分到多个正交子载波，降低单路符号速率。"]};
const channels={AWGN:[1,"只加入加性高斯白噪声，适合建立误码率性能基线。","rxIQ = awgn(txIQ, snrDb, 'measured');"],"瑞利衰落":[1.75,"模拟没有直达径的移动散射环境，包络会出现深衰落。","chan = comm.RayleighChannel('SampleRate', Fs);\nrxIQ = awgn(chan(txIQ), snrDb, 'measured');"],"莱斯衰落":[1.35,"在散射路径之外保留较强直达径，适合空地链路概念演示。","chan = comm.RicianChannel('SampleRate', Fs, 'KFactor', 6);\nrxIQ = awgn(chan(txIQ), snrDb, 'measured');"],"多径信道":[2.1,"加入多条延迟路径，观察码间干扰和均衡器的作用。","pathGain = [1 .5 .25];\nrxIQ = filter(pathGain, 1, txIQ);\nrxIQ = awgn(rxIQ, snrDb, 'measured');"]};
function rng(seed){return()=>{seed|=0;seed=seed+0x6d2b79f5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function data(){const r=rng(s.mod.length*173+s.scheme.length*97+s.snr),bits=Array.from({length:32},()=>r()>.5?1:0),samples=[],points=[],noise=10**(-s.snr/20)*.32;for(let n=0;n<384;n++){let i=Math.floor(n/24)%bits.length,b=bits[i],p=(n%24)/24,v=0;if(s.mod==="2ASK")v=(b?1:.28)*Math.sin(p*Math.PI*2);else if(s.mod==="2FSK")v=Math.sin(p*Math.PI*2*(b?3:1.5));else if(s.mod==="BPSK")v=Math.sin(p*Math.PI*2+(b?0:Math.PI));else if(s.mod==="QPSK")v=Math.sin(p*Math.PI*2+(i%4)*Math.PI/2);else if(s.mod==="16QAM")v=(.35+(i%4)*.2)*Math.sin(p*Math.PI*2+(i%4)*Math.PI/2);else if(s.mod==="MSK")v=Math.sin(p*Math.PI*2*(b?1.25:.75)+i*Math.PI/3);else for(let k=1;k<=6;k++)v+=Math.sin(p*Math.PI*2*k+bits[(i+k)%bits.length]*Math.PI)/5;if(s.scheme==="直接序列扩频")v*=((n*7+3)%11)>5?1:-1;if(s.scheme==="跳频传输")v*=Math.sin((n/24)*Math.PI*(2+i%5));samples.push(v+(r()-.5)*noise)}const levels=[-3,-1,1,3],count=s.mod==="16QAM"?32:24;for(let i=0;i<count;i++){let x=0,y=0;if(["BPSK","2ASK"].includes(s.mod))x=i%2?1:-1;else if(["2FSK","MSK"].includes(s.mod)){x=i%2?.75:-.75;y=i%2?.55:-.55}else if(["16QAM","OFDM"].includes(s.mod)){x=levels[i%4]/3;y=levels[Math.floor(i/4)%4]/3}else{x=i%2?.72:-.72;y=Math.floor(i/2)%2?.72:-.72}points.push([x+(r()-.5)*noise,y+(r()-.5)*noise])}return{samples,points}}
function draw(){const canvas=$("canvas"),rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const c=canvas.getContext("2d"),w=rect.width,h=rect.height,d=data();c.scale(dpr,dpr);c.strokeStyle="rgba(148,163,184,.13)";for(let x=0;x<=w;x+=w/8){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=0;y<=h;y+=h/5){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}c.strokeStyle="rgba(148,163,184,.35)";c.beginPath();c.moveTo(0,h/2);c.lineTo(w,h/2);c.stroke();if(s.view==="wave"){if(s.scheme==="跳频传输"){const colors=["#67e8f9","#c4b5fd","#f9a8d4","#fde68a"];for(let i=0;i<8;i++){c.fillStyle=colors[i%4]+"12";c.fillRect(w/8*i,0,w/8,h)}}const g=c.createLinearGradient(0,0,w,0);g.addColorStop(0,"#67e8f9");g.addColorStop(.55,"#c4b5fd");g.addColorStop(1,"#f9a8d4");c.strokeStyle=g;c.lineWidth=2.2;c.beginPath();d.samples.forEach((v,i)=>{const x=i/(d.samples.length-1)*w,y=h/2-v*h*.32;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}else if(s.view==="spectrum"){const bins=96,vals=Array.from({length:bins},(_,k)=>{let re=0,im=0;for(let n=0;n<d.samples.length;n+=2){const a=-2*Math.PI*k*n/d.samples.length;re+=d.samples[n]*Math.cos(a);im+=d.samples[n]*Math.sin(a)}return Math.log10(1+Math.hypot(re,im))}),max=Math.max(...vals);c.fillStyle="rgba(103,232,249,.18)";c.beginPath();c.moveTo(0,h);vals.forEach((v,i)=>c.lineTo(i/(bins-1)*w,h-v/max*h*.82));c.lineTo(w,h);c.fill();c.strokeStyle="#67e8f9";c.lineWidth=2;c.beginPath();vals.forEach((v,i)=>{const x=i/(bins-1)*w,y=h-v/max*h*.82;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}else{const size=Math.min(w,h)*.72,cx=w/2,cy=h/2;c.strokeStyle="rgba(148,163,184,.28)";c.beginPath();c.moveTo(cx-size/2,cy);c.lineTo(cx+size/2,cy);c.moveTo(cx,cy-size/2);c.lineTo(cx,cy+size/2);c.stroke();d.points.forEach((p,i)=>{c.beginPath();c.fillStyle=i%3?"#f9a8d4":"#67e8f9";c.shadowColor=c.fillStyle;c.shadowBlur=12;c.arc(cx+p[0]*size*.42,cy-p[1]*size*.42,4.5,0,Math.PI*2);c.fill();c.shadowBlur=0})}}
function renderChain(){const short=schemes[s.scheme][0],stages=[["BITS","数据源","生成 0/1 比特流，后续可扩展文本、图像或文件输入。"],["FEC","信道编码","预留卷积码、LDPC 和 Polar 等编码接口。"],["MOD",s.mod,mods[s.mod][2]],["TX",short,schemes[s.scheme][2]],["CH",s.channel,channels[s.channel][1]],["RX","同步与解调","完成同步、匹配滤波、抽样判决和比特恢复。"]];$("chain").innerHTML=stages.map((x,i)=>'<div class="flow"><button class="stage '+(s.stage===i?"active":"")+'" data-i="'+i+'"><span>'+x[0]+'</span><strong>'+x[1]+'</strong><small>'+(i<4?"发送处理":i===4?"传播环境":"接收处理")+'</small></button>'+(i<5?'<i class="arrow">→</i>':"")+'</div>').join("");document.querySelectorAll(".stage").forEach(b=>b.onclick=()=>{s.stage=+b.dataset.i;$("stageName").textContent=stages[s.stage][1];$("stageText").textContent=stages[s.stage][2];renderChain()})}
function codes(){const b=mods[s.mod][0],M=2**b,mod=s.mod==="16QAM"?"txSymbols = qammod(symbolIndex,16,'gray','UnitAveragePower',true);":s.mod==="QPSK"?"txSymbols = pskmod(symbolIndex,4,pi/4,'gray');":s.mod==="BPSK"?"txSymbols = pskmod(bits,2,0,'gray');":"txSymbols = 2*double(bits)-1; % "+s.mod+" 教学映射",transport=s.scheme==="跳频传输"?"baseIQ = repelem(txSymbols,sps);\nhopTable = randperm(16)-1;\nhopSamples = round(1e-3*Fs);\nhopIndex = repelem(repmat(hopTable,1,ceil(numel(baseIQ)/(16*hopSamples))),hopSamples);\nhopIndex = hopIndex(1:numel(baseIQ)).';\nt = (0:numel(baseIQ)-1).'/Fs;\ntxIQ = baseIQ(:).*exp(1j*2*pi*(hopIndex*25e3).*t);":s.scheme==="直接序列扩频"?"chipCode = 2*randi([0 1],8,1)-1;\ntxIQ = kron(txSymbols,chipCode);":s.scheme==="OFDM 多载波"?"grid = reshape(txSymbols(1:floor(end/8)*8),8,[]);\ntxIQ = ifft(grid,8,1); txIQ = txIQ(:);":"txIQ = repelem(txSymbols,sps);";$("txCode").textContent="%% 参数与数据源\nFs = 2e6; Rs = "+s.rate+"e3;\nsps = round(Fs/Rs); snrDb = "+s.snr+";\nbits = randi([0 1],2400,1); M = "+M+";\n\n%% "+s.mod+" 调制\nsymbolIndex = bi2de(reshape(bits,"+b+",[]).','left-msb');\n"+mod+"\n\n%% "+s.scheme+"\n"+transport;$("chCode").textContent="%% "+s.channel+"\n"+channels[s.channel][2];$("rxCode").textContent="%% 体制反变换与同步\nrxBaseband = rxIQ; % 接入解扩、解跳或 OFDM FFT\nrxSync = rxBaseband;\nrxSymbols = rxSync(ceil(sps/2):sps:end);\n\n%% "+s.mod+" 解调\nrxIndex = qamdemod(rxSymbols,M,'gray');\nrxBits = reshape(de2bi(rxIndex,"+b+",'left-msb').',[],1);\n\n%% 性能评价\nL = min(numel(bits),numel(rxBits));\n[errorCount,ber] = biterr(bits(1:L),rxBits(1:L));"}
function update(){s.mod=$("modulation").value;s.scheme=$("scheme").value;s.channel=$("channel").value;s.rate=+$("rate").value;s.snr=+$("snr").value;const m=mods[s.mod],sc=schemes[s.scheme],penalty=channels[s.channel][0],bitrate=s.rate*m[0],band=Math.round(s.rate*m[1]*(s.scheme==="直接序列扩频"?8:s.scheme==="跳频传输"?1.15:1)),evm=Math.min(99,10**(-s.snr/20)*100*penalty),ber=Math.min(.5,.5*Math.exp(-(10**(s.snr/10))/(2.2*penalty))).toExponential(2);$("experiment").textContent=sc[0]+" + "+s.mod;$("rateValue").textContent=s.rate+" kBd";$("snrValue").textContent=s.snr+" dB";$("plotLabel").textContent=s.mod+" · SNR "+s.snr+" dB";$("bitrate").textContent=bitrate;$("bandwidth").textContent=band;$("bps").textContent=m[0];$("scale").textContent=sc[1];$("ber").textContent=ber;$("evm").textContent=evm.toFixed(1)+"%";$("evmText").textContent=evm<12?"星座聚类清晰":"噪声影响明显";$("rxRate").textContent=bitrate;$("modTitle").textContent=s.mod;$("modText").textContent=m[2];$("schemeTitle").textContent=s.scheme;$("schemeText").textContent=sc[2];$("formula").textContent="当前 "+s.mod+"："+s.rate+" kBd × "+m[0]+" bit/sym = "+bitrate+" kbps";$("path").textContent="TX → "+sc[0]+" → "+s.channel+" → RX";$("tags").innerHTML=[s.mod,sc[0],s.channel,"SNR "+s.snr+" dB"].map(x=>"<span>"+x+"</span>").join("");renderChain();codes();draw()}
["modulation","scheme","channel","rate","snr"].forEach(id=>$(id).addEventListener("input",update));document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");s.view=b.dataset.view;$("axis").textContent=s.view==="wave"?"幅度 / 时间":s.view==="spectrum"?"归一化功率 / 频率":"正交分量 Q / 同相分量 I";draw()});window.addEventListener("resize",draw);update();
